[package]
name = "prpg"
version = "0.2.0"
authors = ["Guuuudd <45697827+Guuuudd@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
passwords = "1.1.5"
termion = "1.5.3"